### PR TITLE
Adding support for optional title in Dashboard CRD

### PR DESCRIPTION
**Pull request by unitygilles**
You can add a title, optionally, to the Dashboard resource.

If `title` field not present, the dashboard custom resource will take the same name for the `uid` as the title.

### CODE REVIEW

**Comment by angelbarrera92** [comment]
Looks good to me. Do you think it could make sense to implement the same logic in the embedded `dashboard` attribute on the Organization CRD?

**Comment by dubuc** [comment]
> Looks good to me. Do you think it could make sense to implement the same logic in the embedded `dashboard` attribute on the Organization CRD?

@angelbarrera92 I think it is possible by just adding the title field and having the same logic in the `_create_dashboards` function in `grafana/organization.py` and I am ok with adding it. 

However, do you want to maintain both, the Dashboard CRD and the Org dashboard at feature parity from now on? Not adding it would make it an incentive to move away from the previous Org dashboard.

**Comment by angelbarrera92** [comment]
>@angelbarrera92 I think it is possible by just adding the title field and having the same logic in the _create_dashboards function in grafana/organization.py and I am ok with adding it.
> However, do you want to maintain both, the Dashboard CRD and the Org dashboard at feature parity from now on? Not adding it would make it an incentive to move away from the previous Org dashboard.

Nice point. It could make sense to stop the development in the Org CRD. What do you think @paurosello?

**Comment by paurosello** [comment]
Agree, I think this project is early and should not be much of an issue. I will prepare a small announcement that this feature has been deprecated and everyone should move to the new CRDs

**Review by angelbarrera92 — APPROVED** [review]
LGTM!

**Pull request merged**
